=== hannamark/4xconvert/cgmmweb/resources/cgmm-properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="authentication-service-information">
        <xs:annotation>
        	<xs:documentation>
        		This Element allows specifying required Authentication
        		Service Information. Please refer the caGrid Wiki for
        		more details regarding Authentication Service.
        	</xs:documentation>
        </xs:annotation>
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="service-name"/>
				<xs:element ref="service-url"/>
				<xs:element ref="dorian-information"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="authentication-service-list">
        <xs:annotation>
        	<xs:documentation>
        		This element allows specifying a list of Authentication
        		Services.
        	</xs:documentation>
        </xs:annotation>
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="authentication-service-information" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dorian-information">
        <xs:annotation>
        	<xs:documentation>
        		This element allows specification of caGrid Dorian
        		related information. Please refer the caGrid Wiki for
        		more details regarding Dorian.

        	</xs:documentation>
        </xs:annotation>
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="service-url"/>
				<xs:element ref="proxy-lifetime-hours"/>
				<xs:element ref="proxy-lifetime-minutes"/>
				<xs:element ref="proxy-lifetime-seconds"/>
				<xs:element ref="proxy-delegation-path-length"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cgmm-information">
        <xs:annotation>
        	<xs:documentation>
        		This element allows specification of CGMM related
        		information.
        	</xs:documentation>
        </xs:annotation>
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="cgmm-context-name"/>
				<xs:element ref="cgmm-login-config-file-name"/>				
				<xs:element ref="start-auto-syncgts"/>
				<xs:element ref="cgmm-new-grid-user-creation-disabled"/>
				<xs:element ref="cgmm-new-grid-user-creation-host-redirect-uri"/>
				<xs:element ref="cgmm-alternate-behavior"/>
				<xs:element ref="cgmm-standalone-mode"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="host-application-information">
        <xs:annotation>
        	<xs:documentation>
        		This element allows specification of Host Application
        		related information.
        	</xs:documentation>
        </xs:annotation>
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="host-context-name"/>
				<xs:element ref="host-application-name-for-csm"/>				
				<xs:element ref="host-public-home-page-url"/>
				<xs:element ref="host-user-home-page-url"/>
				<xs:element ref="host-user-login-page-url"/>
				<xs:element ref="host-new-local-user-creation-url"/>
				<xs:element ref="host-mail-jndi-name" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="host-mail-email-id-to" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="host-mail-email-id-from" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="host-mail-email-subject" minOccurs="0" maxOccurs="1"/>		
				<xs:element ref="host-application-logo-url" minOccurs="0" maxOccurs="1"/>		
				<xs:element ref="host-application-logo-alt-text" minOccurs="0" maxOccurs="1"/>		
			
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cgmm-new-grid-user-creation-disabled" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element indicates if the New Grid User Creation
				workflow is disabled for this installation of CGMM. A
				value of true indicates the particular workflow is
				disabled. If disabled the
				cgmm-new-grid-user-creation-host-redirect-url is
				ignored. The value of false indicates that the workflow
				is not disabled. The
				cgmm-new-grid-user-creation-host-redirect-url is
				expected to have valid content.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="cgmm-new-grid-user-creation-host-redirect-uri" type="xs:string" nillable="true">
		<xs:annotation>
			<xs:documentation>
				This element allows specifying the Hosts Redirect URL
				once the New Grid User creation workflow is successfully
				completed. If this workflow is disabled, then the this
				element is ignored.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="cgmm-alternate-behavior" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element allows specifying the CGMM Alternate Behavior. If value is set to 
				'true' then CGMM will redirect requests to Host application. If value is set to 
				'false' then CGMM will forward requests with User related parameters.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="cgmm-standalone-mode" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element allows specifying the Stand Alone Mode for CGMM. In Stand Alone Mode
				the CGMM will not redirect or forward to the host application. Post Migration it will 
				not provide any option to continue to the Host application pages.	
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="cgmm-context-name" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				The Web application context name of CGMM Web
				Application. The default value is cgmmweb
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="cgmm-login-config-file-name" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				The JAAS Login Config file name. This file consists the
				CSM Authentication configuration necessary for
				authentication of CSM users. If the
				java.security.auth.login.config JAAS property is set in
				SystemProperties then this element is ignored and the
				Login Module Configuration for cgmmweb is obtained from
				the particular Login Configuration.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-context-name" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				The Web Application Context name of the Host Web
				Application.This string value must match the web context
				name of the host application.
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="host-application-name-for-csm" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				The Application Name of the Host Web
				Application that is to be used by CSM authentication and authorization. This string value must match the 
				name of the host application available in the CSM Schema.
			</xs:documentation>
		</xs:annotation>
	</xs:element>		
	<xs:element name="host-public-home-page-url" type="xs:string"/>
	<xs:element name="host-user-home-page-url" type="xs:string">	
	<xs:annotation>
			<xs:documentation>
				This element allows specifying the URL for User Home Page of the Host application.
				If kept blank, this element indicates CGMMWeb to use Alternate Behavior. 
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-user-login-page-url" type="xs:string">	
	<xs:annotation>
			<xs:documentation>
				This element can be left blank if 'host-user-home-page-url' is specified and hence Default Behavior is desired.
				However if Alternate Behavior is desired, specify this element with the Login Page URL of the Host Application.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-new-local-user-creation-url" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element OPTIONAL allows specifying the URL for New
				Local User creation workflow of the Host application.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-mail-jndi-name" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element OPTIONAL allows specifying the JNDI Name for the JBoss Mail Service setup.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-mail-email-id-to" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element OPTIONAL allows specifying the 'To' Email Address for emails sent by CGMM to request new accounts.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-mail-email-id-from" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element OPTIONAL allows specifying the 'From' Email Address for emails sent by CGMM to request new accounts.
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-mail-email-subject" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element OPTIONAL allows specifying the Subject of the emails sent by CGMM to request new accounts.	
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-application-logo-url" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element OPTIONAL allows specifying URL for the Application Header Logo.	
			</xs:documentation>
		</xs:annotation></xs:element>
	<xs:element name="host-application-logo-alt-text" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				This element OPTIONAL allows specifying Alt Text for the Application Header Logo.	
			</xs:documentation>
		</xs:annotation></xs:element>
		
	<xs:element name="start-auto-syncgts" type="xs:string"/>
	<xs:element name="service-name" type="xs:string"/>
	<xs:element name="service-url" type="xs:anyURI"/>
	<xs:element name="proxy-lifetime-hours" type="xs:integer"/>
	<xs:element name="proxy-lifetime-minutes" type="xs:integer"/>
	<xs:element name="proxy-lifetime-seconds" type="xs:integer"/>
	<xs:element name="proxy-delegation-path-length" type="xs:integer"/>
	<xs:element name="cgmm-properties">
        <xs:annotation>
        	<xs:documentation>
        		The Root Element of the CGMM Properties. This element
        		allows specifying the CGMM information, Host Application
        		Information and Authentication Service/Dorian
        		Information.
        	</xs:documentation>
        </xs:annotation>
        <xs:complexType>
			<xs:sequence>
				<xs:element ref="cgmm-information"/>
				<xs:element ref="host-application-information"/>
				<xs:element ref="authentication-service-list"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hannamark/4xconvert/cgmmweb/resources/cgmm-properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<cgmm-properties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cgmm-properties.xsd">
<cgmm-information>
		<cgmm-context-name>@cgmm-context-name@</cgmm-context-name>
		<cgmm-login-config-file-name>@cgmm-login-config-file-name@</cgmm-login-config-file-name>
		<start-auto-syncgts>@start-auto-syncgts@</start-auto-syncgts>
		<cgmm-new-grid-user-creation-disabled>@cgmm-new-grid-user-creation-disabled@</cgmm-new-grid-user-creation-disabled>
		<cgmm-new-grid-user-creation-host-redirect-uri>@cgmm-new-grid-user-creation-host-redirect-uri@</cgmm-new-grid-user-creation-host-redirect-uri>
		<cgmm-alternate-behavior>@cgmm-alternate-behavior@</cgmm-alternate-behavior>
		<cgmm-standalone-mode>@cgmm-standalone-mode@</cgmm-standalone-mode>
	</cgmm-information>
	<host-application-information>
		<host-context-name>@host-context-name@</host-context-name>
		<host-application-name-for-csm>@application.context.name@</host-application-name-for-csm>
		<host-public-home-page-url>@host-public-home-page-url@</host-public-home-page-url>
        <host-user-home-page-url>@host-user-home-page-url@</host-user-home-page-url>
        <host-user-login-page-url>@host-user-login-page-url@</host-user-login-page-url>
        <host-new-local-user-creation-url>@host-new-local-user-creation-url@</host-new-local-user-creation-url>
		<host-mail-jndi-name>@mail.jndi.name@</host-mail-jndi-name>
		<host-mail-email-id-to>@host-mail-email-id-to@</host-mail-email-id-to>
		<host-mail-email-id-from>@host-mail-email-id-from@</host-mail-email-id-from>	
		<host-mail-email-subject>@host-mail-email-subject@</host-mail-email-subject>
		<host-application-logo-url>images/appLogo.gif</host-application-logo-url>
		<host-application-logo-alt-text>@host-application-logo-alt-text@</host-application-logo-alt-text>
	</host-application-information>

	<authentication-service-list>
		<authentication-service-information>
			<service-name>@SERVICE_NAME@</service-name>
			<service-url>@CAGRID_AUTHENTICATION_SERVICE_URL@</service-url>
			<dorian-information>
				<service-url>@CAGRID_DORIAN_SERVICE_URL@</service-url>
				<proxy-lifetime-hours>12</proxy-lifetime-hours>
				<proxy-lifetime-minutes>0</proxy-lifetime-minutes>
				<proxy-lifetime-seconds>0</proxy-lifetime-seconds>
				<proxy-delegation-path-length>3</proxy-delegation-path-length>
			</dorian-information>
		</authentication-service-information>
	</authentication-service-list>
</cgmm-properties>
